name: Leonardo CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: leonardo
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: "maven"

      - name: Provide permission to mvnw executable
        run: chmod +x mvnw

      - name: Build and Test with Maven
        env:
          DB_URL: jdbc:postgresql://localhost:5432/leonardo_test
          DB_USERNAME: user
          DB_PASSWORD: password
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        run: ./mvnw clean package -B -Dspring.profiles.active=ci

      - name: Upload test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: '**/target/surefire-reports/'

      - name: Upload Jar file
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: '**/target/*.jar'

      - name: Notify workflow
        if: ${{ always() }}
        run: echo "${{ secrets.MAIL_USERNAME }} and ${{ secrets.MAIL_PASSWORD }}"